//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Category: Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var id: Int64?
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var name: String = "default-name"

    public init(id: Int64?, name: String) {
        self.id = id
        self.name = name
    }

}
