//
// Name.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model name same as property name */
public struct Name: Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var name: Int
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var snakeCase: Int?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var property: String?
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var _123number: Int?

    public init(name: Int, snakeCase: Int?, property: String?, _123number: Int?) {
        self.name = name
        self.snakeCase = snakeCase
        self.property = property
        self._123number = _123number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case snakeCase
        case property
        case _123number
    }

}
