//
// UserAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Vapor
#if canImport(AnyCodable)
import AnyCodable
#endif

        enum CreateUser {
            case http0(value: Void, raw: ClientResponse)
        }

        enum CreateUsersWithArrayInput {
            case http0(value: Void, raw: ClientResponse)
        }

        enum CreateUsersWithListInput {
            case http0(value: Void, raw: ClientResponse)
        }

        enum DeleteUser {
            case http400(value: Void, raw: ClientResponse)
            case http404(value: Void, raw: ClientResponse)
            case http0(value: Void, raw: ClientResponse)
        }

        enum GetUserByName {
            case http200(value: User, raw: ClientResponse)
            case http400(value: Void, raw: ClientResponse)
            case http404(value: Void, raw: ClientResponse)
            case http0(value: User, raw: ClientResponse)
        }

        enum LoginUser {
            case http200(value: String, raw: ClientResponse)
            case http400(value: Void, raw: ClientResponse)
            case http0(value: String, raw: ClientResponse)
        }

        enum LogoutUser {
            case http0(value: Void, raw: ClientResponse)
        }

        enum UpdateUser {
            case http400(value: Void, raw: ClientResponse)
            case http404(value: Void, raw: ClientResponse)
            case http0(value: Void, raw: ClientResponse)
        }


protocol UserAPI {
    /**
     Create user
     POST /user
     This can only be done by the logged in user.
     - parameter body: (body) Created user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUserRaw(body: User, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Create user
     POST /user
     This can only be done by the logged in user.
     - parameter body: (body) Created user object 
     - returns: `EventLoopFuture` of `CreateUser` 
     */
    static func createUser(body: User, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<CreateUser>
    /**
     Creates list of users with given input array
     POST /user/createWithArray
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUsersWithArrayInputRaw(body: [User], headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Creates list of users with given input array
     POST /user/createWithArray
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithArrayInput` 
     */
    static func createUsersWithArrayInput(body: [User], headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<CreateUsersWithArrayInput>
    /**
     Creates list of users with given input array
     POST /user/createWithList
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUsersWithListInputRaw(body: [User], headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Creates list of users with given input array
     POST /user/createWithList
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithListInput` 
     */
    static func createUsersWithListInput(body: [User], headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<CreateUsersWithListInput>
    /**
     Delete user
     DELETE /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) The name that needs to be deleted 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func deleteUserRaw(username: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Delete user
     DELETE /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) The name that needs to be deleted 
     - returns: `EventLoopFuture` of `DeleteUser` 
     */
    static func deleteUser(username: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<DeleteUser>
    /**
     Get user by user name
     GET /user/{username}
     - parameter username: (path) The name that needs to be fetched. Use user1 for testing. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func getUserByNameRaw(username: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Get user by user name
     GET /user/{username}
     - parameter username: (path) The name that needs to be fetched. Use user1 for testing. 
     - returns: `EventLoopFuture` of `GetUserByName` 
     */
    static func getUserByName(username: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<GetUserByName>
    /**
     Logs user into the system
     GET /user/login
     - responseHeaders: [X-Rate-Limit(Int), X-Expires-After(Date)]
     - parameter username: (query) The user name for login 
     - parameter password: (query) The password for login in clear text 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func loginUserRaw(username: String, password: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Logs user into the system
     GET /user/login
     - responseHeaders: [X-Rate-Limit(Int), X-Expires-After(Date)]
     - parameter username: (query) The user name for login 
     - parameter password: (query) The password for login in clear text 
     - returns: `EventLoopFuture` of `LoginUser` 
     */
    static func loginUser(username: String, password: String, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<LoginUser>
    /**
     Logs out current logged in user session
     GET /user/logout
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func logoutUserRaw(headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Logs out current logged in user session
     GET /user/logout
     - returns: `EventLoopFuture` of `LogoutUser` 
     */
    static func logoutUser(headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<LogoutUser>
    /**
     Updated user
     PUT /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) name that need to be deleted 
     - parameter body: (body) Updated user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func updateUserRaw(username: String, body: User, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<ClientResponse>

    /**
     Updated user
     PUT /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) name that need to be deleted 
     - parameter body: (body) Updated user object 
     - returns: `EventLoopFuture` of `UpdateUser` 
     */
    static func updateUser(username: String, body: User, headers: HTTPHeaders, beforeSend: (inout ClientRequest) throws -> ()) -> EventLoopFuture<UpdateUser>
}

extension UserAPI {
    /**
     Create user
     POST /user
     This can only be done by the logged in user.
     - parameter body: (body) Created user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUserRaw(body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let path = "/user"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: User.defaultContentType))
            
            try beforeSend(&request)
        }
    }

    /**
     Create user
     POST /user
     This can only be done by the logged in user.
     - parameter body: (body) Created user object 
     - returns: `EventLoopFuture` of `CreateUser` 
     */
    static func createUser(body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUser> {
        return createUserRaw(body: body, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> CreateUser in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

    /**
     Creates list of users with given input array
     POST /user/createWithArray
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUsersWithArrayInputRaw(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let path = "/user/createWithArray"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: [User].defaultContentType))
            
            try beforeSend(&request)
        }
    }

    /**
     Creates list of users with given input array
     POST /user/createWithArray
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithArrayInput` 
     */
    static func createUsersWithArrayInput(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUsersWithArrayInput> {
        return createUsersWithArrayInputRaw(body: body, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> CreateUsersWithArrayInput in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

    /**
     Creates list of users with given input array
     POST /user/createWithList
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func createUsersWithListInputRaw(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let path = "/user/createWithList"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.POST, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: [User].defaultContentType))
            
            try beforeSend(&request)
        }
    }

    /**
     Creates list of users with given input array
     POST /user/createWithList
     - parameter body: (body) List of user object 
     - returns: `EventLoopFuture` of `CreateUsersWithListInput` 
     */
    static func createUsersWithListInput(body: [User], headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<CreateUsersWithListInput> {
        return createUsersWithListInputRaw(body: body, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> CreateUsersWithListInput in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

    /**
     Delete user
     DELETE /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) The name that needs to be deleted 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func deleteUserRaw(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.DELETE, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }
    }

    /**
     Delete user
     DELETE /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) The name that needs to be deleted 
     - returns: `EventLoopFuture` of `DeleteUser` 
     */
    static func deleteUser(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<DeleteUser> {
        return deleteUserRaw(username: username, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> DeleteUser in
            switch response.status.code {
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

    /**
     Get user by user name
     GET /user/{username}
     - parameter username: (path) The name that needs to be fetched. Use user1 for testing. 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func getUserByNameRaw(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }
    }

    /**
     Get user by user name
     GET /user/{username}
     - parameter username: (path) The name that needs to be fetched. Use user1 for testing. 
     - returns: `EventLoopFuture` of `GetUserByName` 
     */
    static func getUserByName(username: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<GetUserByName> {
        return getUserByNameRaw(username: username, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> GetUserByName in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(User.self, using: Configuration.contentConfiguration.requireDecoder(for: User.defaultContentType)), raw: response)
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: try response.content.decode(User.self, using: Configuration.contentConfiguration.requireDecoder(for: User.defaultContentType)), raw: response)
            }
        }
    }

    /**
     Logs user into the system
     GET /user/login
     - responseHeaders: [X-Rate-Limit(Int), X-Expires-After(Date)]
     - parameter username: (query) The user name for login 
     - parameter password: (query) The password for login in clear text 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func loginUserRaw(username: String, password: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let path = "/user/login"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            struct QueryParams: Content {
                var username: String
                var password: String
            }
            try request.query.encode(QueryParams(username: username, password: password))
            
            try beforeSend(&request)
        }
    }

    /**
     Logs user into the system
     GET /user/login
     - responseHeaders: [X-Rate-Limit(Int), X-Expires-After(Date)]
     - parameter username: (query) The user name for login 
     - parameter password: (query) The password for login in clear text 
     - returns: `EventLoopFuture` of `LoginUser` 
     */
    static func loginUser(username: String, password: String, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<LoginUser> {
        return loginUserRaw(username: username, password: password, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> LoginUser in
            switch response.status.code {
            case 200:
                return .http200(value: try response.content.decode(String.self, using: Configuration.contentConfiguration.requireDecoder(for: String.defaultContentType)), raw: response)
            case 400:
                return .http400(value: (), raw: response)
            default:
                return .http0(value: try response.content.decode(String.self, using: Configuration.contentConfiguration.requireDecoder(for: String.defaultContentType)), raw: response)
            }
        }
    }

    /**
     Logs out current logged in user session
     GET /user/logout
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func logoutUserRaw(headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        let path = "/user/logout"
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.GET, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            
            try beforeSend(&request)
        }
    }

    /**
     Logs out current logged in user session
     GET /user/logout
     - returns: `EventLoopFuture` of `LogoutUser` 
     */
    static func logoutUser(headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<LogoutUser> {
        return logoutUserRaw(headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> LogoutUser in
            switch response.status.code {
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

    /**
     Updated user
     PUT /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) name that need to be deleted 
     - parameter body: (body) Updated user object 
     - returns: `EventLoopFuture` of `ClientResponse` 
     */
    static func updateUserRaw(username: String, body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<ClientResponse> {
        var path = "/user/{username}"
        let usernamePreEscape = String(describing: username)
        let usernamePostEscape = usernamePreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{username}", with: usernamePostEscape, options: .literal, range: nil)
        let URLString = PetstoreClient.basePath + path

        guard let apiClient = Configuration.apiClient else {
            fatalError("Configuration.apiClient is not set.")
        }

        return apiClient.send(.PUT, headers: headers, to: URI(string: URLString)) { request in
            try Configuration.apiWrapper(&request)
            
            
            try request.content.encode(body, using: Configuration.contentConfiguration.requireEncoder(for: User.defaultContentType))
            
            try beforeSend(&request)
        }
    }

    /**
     Updated user
     PUT /user/{username}
     This can only be done by the logged in user.
     - parameter username: (path) name that need to be deleted 
     - parameter body: (body) Updated user object 
     - returns: `EventLoopFuture` of `UpdateUser` 
     */
    static func updateUser(username: String, body: User, headers: HTTPHeaders = PetstoreClient.customHeaders, beforeSend: (inout ClientRequest) throws -> () = { _ in }) -> EventLoopFuture<UpdateUser> {
        return updateUserRaw(username: username, body: body, headers: headers, beforeSend: beforeSend).flatMapThrowing { response -> UpdateUser in
            switch response.status.code {
            case 400:
                return .http400(value: (), raw: response)
            case 404:
                return .http404(value: (), raw: response)
            default:
                return .http0(value: (), raw: response)
            }
        }
    }

}
