//
// DogAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DogAllOf: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var breed: String?

    public init(breed: String?) {
        self.breed = breed
    }

}
