//
// Animal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Animal: Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var className: String
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var color: String? = "red"

    public init(className: String, color: String?) {
        self.className = className
        self.color = color
    }

}
