//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Cat: Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var declawed: Bool?

    public init(declawed: Bool?) {
        self.declawed = declawed
    }

}
