//
// GetAllModelsResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response object containing AllPrimitives object */
public struct GetAllModelsResult: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var myPrimitiveArray: [AllPrimitives]?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var myPrimitive: AllPrimitives?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var myVariableNameTest: VariableNameTest?

    public init(myPrimitiveArray: [AllPrimitives]?, myPrimitive: AllPrimitives?, myVariableNameTest: VariableNameTest?) {
        self.myPrimitiveArray = myPrimitiveArray
        self.myPrimitive = myPrimitive
        self.myVariableNameTest = myVariableNameTest
    }

}
