//
// PersonCardAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PersonCardAllOf: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var firstName: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var lastName: String?

    public init(firstName: String?, lastName: String?) {
        self.firstName = firstName
        self.lastName = lastName
    }

}
