//
// PersonCard.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** This is a card object for a Person derived from BaseCard. */
public struct PersonCard: Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var cardType: String
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var firstName: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var lastName: String?

    public init(cardType: String, firstName: String?, lastName: String?) {
        self.cardType = cardType
        self.firstName = firstName
        self.lastName = lastName
    }

}
