//
// PlaceCardAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlaceCardAllOf: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var placeName: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var placeAddress: String?

    public init(placeName: String?, placeAddress: String?) {
        self.placeName = placeName
        self.placeAddress = placeAddress
    }

}
