//
// SampleSubClassAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SampleSubClassAllOf: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var subClassStringProp: String?
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var subClassIntegerProp: Int?

    public init(subClassStringProp: String?, subClassIntegerProp: Int?) {
        self.subClassStringProp = subClassStringProp
        self.subClassIntegerProp = subClassIntegerProp
    }

}
