//
// FileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FileSchemaTestClass: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var file: File?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var files: [File]?

    public init(file: File?, files: [File]?) {
        self.file = file
        self.files = files
    }

}
