//
// Pet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Pet: Codable {

    public enum Status: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var id: Int64?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var category: Category?
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var name: String
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var photoUrls: [String]
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    public var tags: [Tag]?
    /** pet status in the store */
    public var status: Status?

    public init(id: Int64?, category: Category?, name: String, photoUrls: [String], tags: [Tag]?, status: Status?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}
