//
// AdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct AdditionalPropertiesClass: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var mapString: [String: String]?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var mapMapString: [String: [String: String]]?

    internal init(mapString: [String: String]?, mapMapString: [String: [String: String]]?) {
        self.mapString = mapString
        self.mapMapString = mapMapString
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case mapString = "map_string"
        case mapMapString = "map_map_string"
    }

}
