//
// Animal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct Animal: Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var className: String
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var color: String? = "red"

    internal init(className: String, color: String?) {
        self.className = className
        self.color = color
    }

}
