//
// Capitalization.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct Capitalization: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var smallCamel: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var capitalCamel: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var smallSnake: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var capitalSnake: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var sCAETHFlowPoints: String?
    /** Name of the pet  */
    /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var ATT_NAME: String?

    internal init(smallCamel: String?, capitalCamel: String?, smallSnake: String?, capitalSnake: String?, sCAETHFlowPoints: String?, ATT_NAME: String?) {
        self.smallCamel = smallCamel
        self.capitalCamel = capitalCamel
        self.smallSnake = smallSnake
        self.capitalSnake = capitalSnake
        self.sCAETHFlowPoints = sCAETHFlowPoints
        self.ATT_NAME = ATT_NAME
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case smallCamel
        case capitalCamel
        case smallSnake
        case capitalSnake
        case sCAETHFlowPoints
        case ATT_NAME
    }

}
