//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct Cat: Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    internal var declawed: Bool?

    internal init(declawed: Bool?) {
        self.declawed = declawed
    }

}
