//
// Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct Client: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var client: String?

    internal init(client: String?) {
        self.client = client
    }

}
