//
// File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Must be named &#x60;File&#x60; for test. */
internal struct File: Codable {

    /** Test capitalization */
    /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var sourceURI: String?

    internal init(sourceURI: String?) {
        self.sourceURI = sourceURI
    }

}
