//
// Model200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing model name starting with number */
internal struct Model200Response: Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    internal var name: Int?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var _class: String?

    internal init(name: Int?, _class: String?) {
        self.name = name
        self._class = _class
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case _class
    }

}
