//
// OuterComposite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct OuterComposite: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var myNumber: Double?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var myString: String?
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    internal var myBoolean: Bool?

    internal init(myNumber: Double?, myString: String?, myBoolean: Bool?) {
        self.myNumber = myNumber
        self.myString = myString
        self.myBoolean = myBoolean
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case myNumber
        case myString
        case myBoolean
    }

}
