//
// Pet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct Pet: Codable {

    internal enum Status: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    internal var id: Int64?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var category: Category?
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var name: String
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var photoUrls: [String]
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var tags: [Tag]?
    /** pet status in the store */
    internal var status: Status?

    internal init(id: Int64?, category: Category?, name: String, photoUrls: [String], tags: [Tag]?, status: Status?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}
