//
// ReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct ReadOnlyFirst: Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var bar: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var baz: String?

    internal init(bar: String?, baz: String?) {
        self.bar = bar
        self.baz = baz
    }

}
