//
// Return.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing reserved words */
internal struct Return: Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    internal var _return: Int?

    internal init(_return: Int?) {
        self._return = _return
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case _return = "return"
    }

}
