//
// TypeHolderDefault.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

internal struct TypeHolderDefault: Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var stringItem: String = "what"
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var numberItem: Double
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var integerItem: Int
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var boolItem: Bool = true
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    internal var arrayItem: [Int]

    internal init(stringItem: String, numberItem: Double, integerItem: Int, boolItem: Bool, arrayItem: [Int]) {
        self.stringItem = stringItem
        self.numberItem = numberItem
        self.integerItem = integerItem
        self.boolItem = boolItem
        self.arrayItem = arrayItem
    }

    internal enum CodingKeys: String, CodingKey, CaseIterable {
        case stringItem = "string_item"
        case numberItem = "number_item"
        case integerItem = "integer_item"
        case boolItem = "bool_item"
        case arrayItem = "array_item"
    }

}
