//
// AdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class AdditionalPropertiesClass: NSObject, Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var mapString: [String: String]?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var mapMapString: [String: [String: String]]?

    public init(mapString: [String: String]?, mapMapString: [String: [String: String]]?) {
        self.mapString = mapString
        self.mapMapString = mapMapString
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mapString
        case mapMapString
    }

}
