//
// Animal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class Animal: NSObject, Codable {

        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var _className: String
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var color: String? = "red"

    public init(_className: String, color: String?) {
        self._className = _className
        self.color = color
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _className = "className"
        case color
    }

}
