//
// ApiResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class ApiResponse: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var code: Int?
    @objc public var codeNum: NSNumber? {
        get {
            return code as? NSNumber
        }
    }
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var type: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var message: String?

    public init(code: Int?, type: String?, message: String?) {
        self.code = code
        self.type = type
        self.message = message
    }

}
