//
// Cat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class Cat: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var declawed: Bool?
    @objc public var declawedNum: NSNumber? {
        get {
            return declawed as? NSNumber
        }
    }

    public init(declawed: Bool?) {
        self.declawed = declawed
    }

}
