//
// Category.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class Category: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var _id: Int64?
    @objc public var _idNum: NSNumber? {
        get {
            return _id as NSNumber?
        }
    }
        /** DEBUG - required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var name: String = "default-name"

    public init(_id: Int64?, name: String) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case name
    }

}
