//
// Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class Client: NSObject, Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var client: String?

    public init(client: String?) {
        self.client = client
    }

}
