//
// File.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Must be named &#x60;File&#x60; for test. */

@objc public class File: NSObject, Codable {

    /** Test capitalization */
    /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var sourceURI: String?

    public init(sourceURI: String?) {
        self.sourceURI = sourceURI
    }

}
