//
// HasOnlyReadOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class HasOnlyReadOnly: NSObject, Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var bar: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var foo: String?

    public init(bar: String?, foo: String?) {
        self.bar = bar
        self.foo = foo
    }

}
