//
// MixedPropertiesAndAdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class MixedPropertiesAndAdditionalPropertiesClass: NSObject, Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var uuid: UUID?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var dateTime: Date?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var map: [String: Animal]?

    public init(uuid: UUID?, dateTime: Date?, map: [String: Animal]?) {
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

}
