//
// OuterComposite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class OuterComposite: NSObject, Codable {

        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var myNumber: Double?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var myString: String?
        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var myBoolean: Bool?
    @objc public var myBooleanNum: NSNumber? {
        get {
            return myBoolean as? NSNumber
        }
    }

    public init(myNumber: Double?, myString: String?, myBoolean: Bool?) {
        self.myNumber = myNumber
        self.myString = myString
        self.myBoolean = myBoolean
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case myNumber
        case myString
        case myBoolean
    }

}
