//
// Return.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Model for testing reserved words */

@objc public class Return: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var _return: Int?
    @objc public var _returnNum: NSNumber? {
        get {
            return _return as? NSNumber
        }
    }

    public init(_return: Int?) {
        self._return = _return
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _return
    }

}
