//
// SpecialModelName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class SpecialModelName: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var specialPropertyName: Int64?
    @objc public var specialPropertyNameNum: NSNumber? {
        get {
            return specialPropertyName as? NSNumber
        }
    }

    public init(specialPropertyName: Int64?) {
        self.specialPropertyName = specialPropertyName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case specialPropertyName = "$special[property.name]"
    }

}
