//
// User.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

@objc public class User: NSObject, Codable {

        /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var _id: Int64?
    @objc public var _idNum: NSNumber? {
        get {
            return _id as NSNumber?
        }
    }
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var username: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var firstName: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var lastName: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var email: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var password: String?
        /** DEBUG - !required|!isNullable|!vendorExtensions.x-swift-optional-scalar */
    @objc public var phone: String?
    /** User Status */
    /** DEBUG - !required|!isNullable|vendorExtensions.x-swift-optional-scalar */
    public var userStatus: Int?
    @objc public var userStatusNum: NSNumber? {
        get {
            return userStatus as NSNumber?
        }
    }

    public init(_id: Int64?, username: String?, firstName: String?, lastName: String?, email: String?, password: String?, phone: String?, userStatus: Int?) {
        self._id = _id
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
        self.password = password
        self.phone = phone
        self.userStatus = userStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _id = "id"
        case username
        case firstName
        case lastName
        case email
        case password
        case phone
        case userStatus
    }

}
