//
// PetstoreClientModelEnumArrays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelEnumArrays: Codable {

    public enum PetstoreClientModelJustSymbol: String, Codable, CaseIterable {
        case greaterThanOrEqualTo = ">="
        case dollar = "$"
    }
    public enum PetstoreClientModelArrayEnum: String, Codable, CaseIterable {
        case fish = "fish"
        case crab = "crab"
    }
    public var justSymbol: PetstoreClientModelJustSymbol?
    public var arrayEnum: [PetstoreClientModelArrayEnum]?

    public init(justSymbol: PetstoreClientModelJustSymbol?, arrayEnum: [PetstoreClientModelArrayEnum]?) {
        self.justSymbol = justSymbol
        self.arrayEnum = arrayEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case justSymbol = "just_symbol"
        case arrayEnum = "array_enum"
    }

}

}
