//
// PetstoreClientModelssssDPet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssDPet: Codable {

    public enum PetstoreClientModelssssDStatus: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var id: Int64?
    public var category: PetstoreClientModelssssDCategory?
    public var name: String
    public var photoUrls: [String]
    public var tags: [PetstoreClientModelssssDTag]?
    /** pet status in the store */
    public var status: PetstoreClientModelssssDStatus?

    public init(id: Int64?, category: PetstoreClientModelssssDCategory?, name: String, photoUrls: [String], tags: [PetstoreClientModelssssDTag]?, status: PetstoreClientModelssssDStatus?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}

}
