//
// PetstoreClientModel.Pet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.Pet: Codable {

    public enum PetstoreClientModel.Status: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var id: Int64?
    public var category: PetstoreClientModel.Category?
    public var name: String
    public var photoUrls: [String]
    public var tags: [PetstoreClientModel.Tag]?
    /** pet status in the store */
    public var status: PetstoreClientModel.Status?

    public init(id: Int64?, category: PetstoreClientModel.Category?, name: String, photoUrls: [String], tags: [PetstoreClientModel.Tag]?, status: PetstoreClientModel.Status?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}

}
