//
// PetstoreClientModelssssDEnumClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public enum PetstoreClientModelssssDEnumClass: String, Codable, CaseIterable {
    case abc = "_abc"
    case efg = "-efg"
    case xyz = "(xyz)"
}

}
