//
// PetstoreClientModelssssPet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssPet: Codable {

    public enum PetstoreClientModelssssStatus: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var id: Int64?
    public var category: PetstoreClientModelssssCategory?
    public var name: String
    public var photoUrls: [String]
    public var tags: [PetstoreClientModelssssTag]?
    /** pet status in the store */
    public var status: PetstoreClientModelssssStatus?

    public init(id: Int64?, category: PetstoreClientModelssssCategory?, name: String, photoUrls: [String], tags: [PetstoreClientModelssssTag]?, status: PetstoreClientModelssssStatus?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}

}
