//
// PetstoreClientModel.EnumTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.EnumTest: Codable {

    public enum PetstoreClientModel.EnumString: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModel.EnumStringRequired: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModel.EnumInteger: Int, Codable, CaseIterable {
        case _1 = 1
        case number1 = -1
    }
    public enum PetstoreClientModel.EnumNumber: Double, Codable, CaseIterable {
        case _11 = 1.1
        case number12 = -1.2
    }
    public var enumString: PetstoreClientModel.EnumString?
    public var enumStringRequired: PetstoreClientModel.EnumStringRequired
    public var enumInteger: PetstoreClientModel.EnumInteger?
    public var enumNumber: PetstoreClientModel.EnumNumber?
    public var outerEnum: PetstoreClientModel.OuterEnum?

    public init(enumString: PetstoreClientModel.EnumString?, enumStringRequired: PetstoreClientModel.EnumStringRequired, enumInteger: PetstoreClientModel.EnumInteger?, enumNumber: PetstoreClientModel.EnumNumber?, outerEnum: PetstoreClientModel.OuterEnum?) {
        self.enumString = enumString
        self.enumStringRequired = enumStringRequired
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enumString = "enum_string"
        case enumStringRequired = "enum_string_required"
        case enumInteger = "enum_integer"
        case enumNumber = "enum_number"
        case outerEnum
    }

}

}
