//
// PetstoreClientModelssssDFileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssDFileSchemaTestClass: Codable {

    public var file: PetstoreClientModelssssDFile?
    public var files: [PetstoreClientModelssssDFile]?

    public init(file: PetstoreClientModelssssDFile?, files: [PetstoreClientModelssssDFile]?) {
        self.file = file
        self.files = files
    }

}

}
