//
// PetstoreClientModelssssEnumTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssEnumTest: Codable {

    public enum PetstoreClientModelssssEnumString: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelssssEnumStringRequired: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelssssEnumInteger: Int, Codable, CaseIterable {
        case _1 = 1
        case number1 = -1
    }
    public enum PetstoreClientModelssssEnumNumber: Double, Codable, CaseIterable {
        case _11 = 1.1
        case number12 = -1.2
    }
    public var enumString: PetstoreClientModelssssEnumString?
    public var enumStringRequired: PetstoreClientModelssssEnumStringRequired
    public var enumInteger: PetstoreClientModelssssEnumInteger?
    public var enumNumber: PetstoreClientModelssssEnumNumber?
    public var outerEnum: PetstoreClientModelssssOuterEnum?

    public init(enumString: PetstoreClientModelssssEnumString?, enumStringRequired: PetstoreClientModelssssEnumStringRequired, enumInteger: PetstoreClientModelssssEnumInteger?, enumNumber: PetstoreClientModelssssEnumNumber?, outerEnum: PetstoreClientModelssssOuterEnum?) {
        self.enumString = enumString
        self.enumStringRequired = enumStringRequired
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enumString = "enum_string"
        case enumStringRequired = "enum_string_required"
        case enumInteger = "enum_integer"
        case enumNumber = "enum_number"
        case outerEnum
    }

}

}
