//
// PetstoreClientModelReturn.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

/** Model for testing reserved words */
public struct PetstoreClientModelReturn: Codable {

    public var _return: Int?

    public init(_return: Int?) {
        self._return = _return
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _return = "return"
    }

}

}
