//
// PetstoreClientModelssssD200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

/** Model for testing model name starting with number */
public struct PetstoreClientModelssssD200Response: Codable {

    public var name: Int?
    public var _class: String?

    public init(name: Int?, _class: String?) {
        self.name = name
        self._class = _class
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case _class = "class"
    }

}

}
