//
// PetstoreClientModelssssDClassModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

/** Model for testing model with \&quot;_class\&quot; property */
public struct PetstoreClientModelssssDClassModel: Codable {

    public var _class: String?

    public init(_class: String?) {
        self._class = _class
    }

}

}
