//
// PetstoreClientModel.NumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.NumberOnly: Codable {

    public var justNumber: Double?

    public init(justNumber: Double?) {
        self.justNumber = justNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case justNumber = "JustNumber"
    }

}

}
