//
// PetstoreClientModelReadOnlyFirst.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelReadOnlyFirst: Codable {

    public var bar: String?
    public var baz: String?

    public init(bar: String?, baz: String?) {
        self.bar = bar
        self.baz = baz
    }

}

}
