//
// PetstoreClientModelEnumTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelEnumTest: Codable {

    public enum PetstoreClientModelEnumString: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelEnumStringRequired: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelEnumInteger: Int, Codable, CaseIterable {
        case _1 = 1
        case number1 = -1
    }
    public enum PetstoreClientModelEnumNumber: Double, Codable, CaseIterable {
        case _11 = 1.1
        case number12 = -1.2
    }
    public var enumString: PetstoreClientModelEnumString?
    public var enumStringRequired: PetstoreClientModelEnumStringRequired
    public var enumInteger: PetstoreClientModelEnumInteger?
    public var enumNumber: PetstoreClientModelEnumNumber?
    public var outerEnum: PetstoreClientModelOuterEnum?

    public init(enumString: PetstoreClientModelEnumString?, enumStringRequired: PetstoreClientModelEnumStringRequired, enumInteger: PetstoreClientModelEnumInteger?, enumNumber: PetstoreClientModelEnumNumber?, outerEnum: PetstoreClientModelOuterEnum?) {
        self.enumString = enumString
        self.enumStringRequired = enumStringRequired
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enumString = "enum_string"
        case enumStringRequired = "enum_string_required"
        case enumInteger = "enum_integer"
        case enumNumber = "enum_number"
        case outerEnum
    }

}

}
