//
// PetstoreClientModel.FileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.FileSchemaTestClass: Codable {

    public var file: PetstoreClientModel.File?
    public var files: [PetstoreClientModel.File]?

    public init(file: PetstoreClientModel.File?, files: [PetstoreClientModel.File]?) {
        self.file = file
        self.files = files
    }

}

}
