//
// PetstoreClientModelssssFileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssFileSchemaTestClass: Codable {

    public var file: PetstoreClientModelssssFile?
    public var files: [PetstoreClientModelssssFile]?

    public init(file: PetstoreClientModelssssFile?, files: [PetstoreClientModelssssFile]?) {
        self.file = file
        self.files = files
    }

}

}
