//
// PetstoreClientModelPet.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelPet: Codable {

    public enum PetstoreClientModelStatus: String, Codable, CaseIterable {
        case available = "available"
        case pending = "pending"
        case sold = "sold"
    }
    public var id: Int64?
    public var category: PetstoreClientModelCategory?
    public var name: String
    public var photoUrls: [String]
    public var tags: [PetstoreClientModelTag]?
    /** pet status in the store */
    public var status: PetstoreClientModelStatus?

    public init(id: Int64?, category: PetstoreClientModelCategory?, name: String, photoUrls: [String], tags: [PetstoreClientModelTag]?, status: PetstoreClientModelStatus?) {
        self.id = id
        self.category = category
        self.name = name
        self.photoUrls = photoUrls
        self.tags = tags
        self.status = status
    }

}

}
