//
// PetstoreClientModelssssDAnimalFarm.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public typealias PetstoreClientModelssssDAnimalFarm = [PetstoreClientModelssssDAnimal]

}
