//
// PetstoreClientModelssssDFile.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

/** Must be named &#x60;File&#x60; for test. */
public struct PetstoreClientModelssssDFile: Codable {

    /** Test capitalization */
    public var sourceURI: String?

    public init(sourceURI: String?) {
        self.sourceURI = sourceURI
    }

}

}
