//
// PetstoreClientModelssssOuterEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public enum PetstoreClientModelssssOuterEnum: String, Codable, CaseIterable {
    case placed = "placed"
    case approved = "approved"
    case delivered = "delivered"
}

}
