//
// PetstoreClientModelssssDEnumArrays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssDEnumArrays: Codable {

    public enum PetstoreClientModelssssDJustSymbol: String, Codable, CaseIterable {
        case greaterThanOrEqualTo = ">="
        case dollar = "$"
    }
    public enum PetstoreClientModelssssDArrayEnum: String, Codable, CaseIterable {
        case fish = "fish"
        case crab = "crab"
    }
    public var justSymbol: PetstoreClientModelssssDJustSymbol?
    public var arrayEnum: [PetstoreClientModelssssDArrayEnum]?

    public init(justSymbol: PetstoreClientModelssssDJustSymbol?, arrayEnum: [PetstoreClientModelssssDArrayEnum]?) {
        self.justSymbol = justSymbol
        self.arrayEnum = arrayEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case justSymbol = "just_symbol"
        case arrayEnum = "array_enum"
    }

}

}
