//
// PetstoreClientModelssssMixedPropertiesAndAdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssMixedPropertiesAndAdditionalPropertiesClass: Codable {

    public var uuid: UUID?
    public var dateTime: Date?
    public var map: [String: PetstoreClientModelssssAnimal]?

    public init(uuid: UUID?, dateTime: Date?, map: [String: PetstoreClientModelssssAnimal]?) {
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

}

}
