//
// PetstoreClientModelOrder.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelOrder: Codable {

    public enum PetstoreClientModelStatus: String, Codable, CaseIterable {
        case placed = "placed"
        case approved = "approved"
        case delivered = "delivered"
    }
    public var id: Int64?
    public var petId: Int64?
    public var quantity: Int?
    public var shipDate: Date?
    /** Order Status */
    public var status: PetstoreClientModelStatus?
    public var complete: Bool? = false

    public init(id: Int64?, petId: Int64?, quantity: Int?, shipDate: Date?, status: PetstoreClientModelStatus?, complete: Bool?) {
        self.id = id
        self.petId = petId
        self.quantity = quantity
        self.shipDate = shipDate
        self.status = status
        self.complete = complete
    }

}

}
