//
// PetstoreClientModel.DogAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.DogAllOf: Codable {

    public var breed: String?

    public init(breed: String?) {
        self.breed = breed
    }

}

}
