//
// PetstoreClientModelssssDCategory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssDCategory: Codable {

    public var id: Int64?
    public var name: String = "default-name"

    public init(id: Int64?, name: String) {
        self.id = id
        self.name = name
    }

}

}
