//
// PetstoreClientModel.Client.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.Client: Codable {

    public var client: String?

    public init(client: String?) {
        self.client = client
    }

}

}
