//
// PetstoreClientModelFileSchemaTestClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelFileSchemaTestClass: Codable {

    public var file: PetstoreClientModelFile?
    public var files: [PetstoreClientModelFile]?

    public init(file: PetstoreClientModelFile?, files: [PetstoreClientModelFile]?) {
        self.file = file
        self.files = files
    }

}

}
