//
// PetstoreClientModelssssDEnumTest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssDEnumTest: Codable {

    public enum PetstoreClientModelssssDEnumString: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelssssDEnumStringRequired: String, Codable, CaseIterable {
        case upper = "UPPER"
        case lower = "lower"
        case empty = ""
    }
    public enum PetstoreClientModelssssDEnumInteger: Int, Codable, CaseIterable {
        case _1 = 1
        case number1 = -1
    }
    public enum PetstoreClientModelssssDEnumNumber: Double, Codable, CaseIterable {
        case _11 = 1.1
        case number12 = -1.2
    }
    public var enumString: PetstoreClientModelssssDEnumString?
    public var enumStringRequired: PetstoreClientModelssssDEnumStringRequired
    public var enumInteger: PetstoreClientModelssssDEnumInteger?
    public var enumNumber: PetstoreClientModelssssDEnumNumber?
    public var outerEnum: PetstoreClientModelssssDOuterEnum?

    public init(enumString: PetstoreClientModelssssDEnumString?, enumStringRequired: PetstoreClientModelssssDEnumStringRequired, enumInteger: PetstoreClientModelssssDEnumInteger?, enumNumber: PetstoreClientModelssssDEnumNumber?, outerEnum: PetstoreClientModelssssDOuterEnum?) {
        self.enumString = enumString
        self.enumStringRequired = enumStringRequired
        self.enumInteger = enumInteger
        self.enumNumber = enumNumber
        self.outerEnum = outerEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enumString = "enum_string"
        case enumStringRequired = "enum_string_required"
        case enumInteger = "enum_integer"
        case enumNumber = "enum_number"
        case outerEnum
    }

}

}
