//
// PetstoreClientModelHasOnlyReadOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelHasOnlyReadOnly: Codable {

    public var bar: String?
    public var foo: String?

    public init(bar: String?, foo: String?) {
        self.bar = bar
        self.foo = foo
    }

}

}
