//
// PetstoreClientModelssssEnumArrays.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelssssEnumArrays: Codable {

    public enum PetstoreClientModelssssJustSymbol: String, Codable, CaseIterable {
        case greaterThanOrEqualTo = ">="
        case dollar = "$"
    }
    public enum PetstoreClientModelssssArrayEnum: String, Codable, CaseIterable {
        case fish = "fish"
        case crab = "crab"
    }
    public var justSymbol: PetstoreClientModelssssJustSymbol?
    public var arrayEnum: [PetstoreClientModelssssArrayEnum]?

    public init(justSymbol: PetstoreClientModelssssJustSymbol?, arrayEnum: [PetstoreClientModelssssArrayEnum]?) {
        self.justSymbol = justSymbol
        self.arrayEnum = arrayEnum
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case justSymbol = "just_symbol"
        case arrayEnum = "array_enum"
    }

}

}
