//
// PetstoreClientModel.MixedPropertiesAndAdditionalPropertiesClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.MixedPropertiesAndAdditionalPropertiesClass: Codable {

    public var uuid: UUID?
    public var dateTime: Date?
    public var map: [String:PetstoreClientModel.Animal]?

    public init(uuid: UUID?, dateTime: Date?, map: [String:PetstoreClientModel.Animal]?) {
        self.uuid = uuid
        self.dateTime = dateTime
        self.map = map
    }

}

}
