//
// PetstoreClientModel.CatAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModel.CatAllOf: Codable {

    public var declawed: Bool?

    public init(declawed: Bool?) {
        self.declawed = declawed
    }

}

}
