//
// PetstoreClientModelArrayOfNumberOnly.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

extension PetstoreClientModel {

public struct PetstoreClientModelArrayOfNumberOnly: Codable {

    public var arrayNumber: [Double]?

    public init(arrayNumber: [Double]?) {
        self.arrayNumber = arrayNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case arrayNumber = "ArrayNumber"
    }

}

}
